### ISSUE TITLE
Tab as indent

### ISSUE THREAD

**Issue by yoann9344** [Abdelaziz18003/vscode-quasar-snippets#15]
Hi, I saw you had my jade's snippets to your git, thx !
But actually it would be better to put snippets without spaces but with tabulations instead ("\t").
Because tabulations are easily handled by Vs code, for example :
You use 2 spaces indent in your snippets, and I use 4. With \t Vs code will automatically indent with my configuration, no need to use a beautifier. And it works for all configuration.
You can see the way I transform it in my HTML snippets to jade snippets converter.

By the way I think you should keep the python script somewhere there, I think I would be easier to update jade snippets if someone add few HTML snippets.

If you don't feel confident with it or have a lack of time I can do the script to add tabulations to your HTML snippets.

**Comment by Abdelaziz18003** [comment]
Hi @yoann9344 thanks for your interest and nice contribution.
Yes, I totally agree to use `\t` instead of `2 spaces` indentation. I just test it and it works fine as you described it. I used `2 spaces` before because the vue community is using it. But as you have said `\t` is a more generic solution.
I saw in your auto-generated file some `\\t` indentation and when I tested them I saw that they are output as `\\t` not as indentations, so I replaced all `\\t` and `\t` with `2 spaces`. But, as I can see now, `\t` are working correctly. To replace `2 spaces` with `\t` I think that vscode `search and replace` is sufficient to do that.
For the python script to generate `pug` snippets. I think creating an npm module based on nodejs and adding it as a dependency to the `package.json` file will be a cleaner solution for that. I will do that as soon as possible.
Thanks for your contribution and I am open for any other suggestions.

**Comment by yoann9344** [comment]
Yeah I did a mistake, and I have forgotten to put the last version. I don't have any experience with GitHub, so I have to accommodate my self to it !

Yeah I agree a node module would perfect, but I'm still not confident enough with it. I'll update my files to have a clean version until you create a node_module for doing the job ;)

Edit : this the working version of my jade python script, which keep order of HTML snippets, like this if someone need it in the future, the script will available in this topic.

```python
# https://github.com/Abdelaziz18003/vscode-quasar-snippets/

# install html2pug in global or add it to os's path
# npm install -g html2pug
import json
import os
import re
from collections import OrderedDict


with open("snippets.json", "r") as read_file:
    data = json.load(read_file, object_pairs_hook=OrderedDict)


# extract body
for (key, value) in data.items():
    ## debuging
    # if value['prefix'] != 'qactionsheet':
    # if value['prefix'] != 'qcardmedia':
    #     continue

    # convert body list to string
    body = '\n'.join(value['body'])

    # save body in a tmp file
    with open('tmp.html', 'w') as tmp:
        tmp.write(body)

    # render to html
    # handle indentation as TAB (-t) for better user experience (vs code handle tabs depending on user settings)
    # (should not work on windows)
    os.system('html2pug < tmp.html > tmp.pug -f -t')

    # extract the rendered file
    with open('tmp.pug', 'r') as out_pug:
        result = out_pug.readlines()

    # remove blank and new lines at the end of each item (new lines will be handle by vs code)
    result = [item.rstrip() for item in result]
    print(result)

    # 1/ fix html2pug tab issue, (some indent are not recognized, this issue let some spaces instead of '\t',
    # see option -t in html to pug
    # 2/ blank line issue
    def number_spaces_at_beginning(string):
        number_spaces = 0
        for c in string:
            if c == ' ':
                number_spaces += 1
            else:
                break
        return number_spaces
    deleted_lines = 0
    for index, item in enumerate(result):
        # 2/
        if item == '':
            del result[index]
            deleted_lines += 1

        number_spaces = number_spaces_at_beginning(item)
        if number_spaces == 0:
            continue
        number_tab = number_spaces//2

        # 1/
        result[index-deleted_lines] = re.sub('^'+' '*number_spaces, '\t'*number_tab, item)
    # end fixing

    value['body'] = result
    print(result)

with open('pug.json', 'w') as result_file:
    json.dump(data, result_file, indent=4)
```
