### ISSUE TITLE
Add Flex CSS snippets

### ISSUE THREAD

**Issue by khuguet-tfg** [Abdelaziz18003/vscode-quasar-snippets#6]
Add snippets for [Flex CSS](https://quasar-framework.org/components/flex-css.html).
Suggested Snippets:
* qrow
* qcol

Others might be nice to have for responsive design (qcol6, qcolauto, ect...).  We can discuss some thoughts on this further if you think it would be good to add.

I can make a PR to suggest the implementation.

**Comment by Abdelaziz18003** [comment]
@khuguet-tfg Thanks for the suggestion. It will be nice if you can show me here (in a comment) a single snippet of how you want to implement `qrow` for example so we can discuss it.

**Comment by khuguet-tfg** [comment]
This would probably be how I was start.  There are some additional ones that might be helpful especially for beginners that have trouble with the different layout options for a row (start, end, between, around, and center)
``` javascript
    "QRow": {
        "prefix": "qrow",
        "body": [
            "<div class=\"row$1\">",
            "  $2",
            "</div>"
        ],
        "description": "Flex row"
    },
    "QCol": {
        "prefix": "qcol",
        "body": [
            "<div class=\"${1:col}\">",
            "  $2",
            "</div>"
        ],
        "description": "Flex col, that by default fills remaining available space in a row"
    }
```

**Comment by Abdelaziz18003** [comment]
Ok thanks for the examples and for your time :)
Honestly, I can see some issues with this approach for a couple of reasons:

1. This extension is primarily made for **Quasar Components** so that for example `qcard` is `<q-card></q-card>` and this pattern is followed in all snippets. adding `qrow` for example will break this pattern and may make users think it is a new component `<q-row></q-row>`.

2. I think VSCode default Emmet can handle that sort of things better and in fewer lines of code ex `.row = <div class="row"></div>`, `.row.justify-start = <div class="row justify-start"></div>`. Making a snippet for every combination of classes will not be possible. and making one for each class will make the snippets list bigger while not being very useful in my opinion since we tend to have multiple classes per element usually.

3. This will restrict the use of layout classes to `div` elements only, while they can be used with other elements ex: `section`, `ul` .. etc.

4. Completing the rest of components has the highest priority now. I think it will be frustrating for users if we start adding new snippets other than components now. But your suggestion will be taken into consideration once components are done. We may also discuss and search for a suitable method to implement it later.

This is my opinion about it :)

**Comment by khuguet-tfg** [comment]
No biggie, I just thought I would make the suggestion.  I can see your points especially for a common snippet extension that will be used in different scenarios.  I like you suggestion to use Emmit instead, but it is lacking in the intelli-sense that snippets bring.  I will probably adapt some form of it (in User Snippets) with some adjustments to handle your 3rd point.  For example:
``` javascript
    "QCssRow": {
        "prefix": "qcssrow",
        "body": [
            "<${1:div} class=\"row$2\">",
            "  $2",
            "</$1>"
        ],
        "description": "Flex row"
    }
```
This will default to div, but can easily change the element type.

If you have some other components that need to be added let me know and I will see if I can make some time.

**Comment by Abdelaziz18003** [comment]
I invite you to share your user snippets in a public repository. So we can use them and maybe find a way to integrate them here later.
Other than that, if you want to contribute by adding more components you are more than welcome. It is hard for me to add all components myself and I will appreciate if you have some time to help improving the snippets.
Here is where to start https://quasar-framework.org/components/action-sheet.html. please make sure you also read the small contribution guide on the readme file to keep things consistent. I will create some issues to keep things organized and help other devs who want to contribute. Feel free to assign yourself to any issue you want to work on. Your effort is appreciated :heart:
